# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileCopyrightText: Tristan Partin <tristan@partin.io>

version = 1
SPDX-HomePage = "https://git.sr.ht/~tristan957/resume"
SPDX-PackageName = "resume"

[[annotations]]
path = [
    "package.json",
    "yarn.lock",
]
precedence = "override"
SPDX-FileCopyrightText = "Tristan Partin <tristan@partin.io>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "images/sourcehut.svg",
]
precedence = "override"
SPDX-FileCopyrightText = "sourcehut"
SPDX-License-Identifier = "CC0-1.0"
